const storeConstants = {
  GET_ANALYSIS_DATA_ALL: 'GET_ANALYSIS_DATA_ALL',
  GET_ANALYSIS_REAL_DATA: 'GET_ANALYSIS_REAL_DATA',

  GET_FIRM_BACKGROUND_DATA: 'GET_FIRM_BACKGROUND_DATA',

  FIRM_BACKGROUND_SELECT: 'FIRM_BACKGROUND_SELECT',

  GET_LAST_CUSTOM_SCENARIO: 'GET_LAST_CUSTOM_SCENARIO',
  ENABLE_CUSTOM_SCENARIO: 'ENABLE_CUSTOM_SCENARIO',
  DISABLE_CUSTOM_SCENARIO: 'DISABLE_CUSTOM_SCENARIO',
  LOADER: 'LOADER',

  DISABLE_BUTTON: 'DISABLE_BUTTON',
  DISABLE_BUTTON_FX: 'DISABLE_BUTTON_FX',
  DISABLE_BUTTON_MATURITY: 'DISABLE_BUTTON_MATURITY',

  // Real Analysis fetch
  REAL_FINANCIAL_STATEMENTS_FETCH_DATA: 'REAL_FINANCIAL_STATEMENTS_FETCH_DATA',
  REAL_FX_POSITION_FETCH_DATA: 'REAL_FX_POSITION_FETCH_DATA',
  REAL_MATURITY_SHORT_TERM_FETCH_DATA: 'REAL_MATURITY_SHORT_TERM_FETCH_DATA',
  REAL_BUSINESS_PLAN_FETCH_DATA: 'REAL_BUSINESS_PLAN_FETCH_DATA',
  REAL_CUSTOM_SCENARIO_FETCH_DATA: 'REAL_CUSTOM_SCENARIO_FETCH_DATA',
  // Fınancıal Analysis fetch

  NEW_POST_FIRM_BACKGROUND: 'NEW_POST_FIRM_BACKGROUND',
  CHANGE_CATAGORY: 'CHANGE_CATAGORY',
  CATAGORY_SUCCESS: 'CATAGORY_SUCCESS',

  //Register Login
  GET_LEADS: 'GET_LEADS',
  DELETE_LEAD: 'DELETE_LEAD',
  ADD_LEAD: 'ADD_LEAD',
  USER_LOADING: 'USER_LOADING',
  USER_INFO: 'USER_INFO',
  RESET_TOKEN: 'RESET_TOKEN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CLEAR_LEADS: 'CLEAR_LEADS',

  //MyFirm
  GET_MY_SHOW_FIRM: 'GET_MY_SHOW_FIRM',
  ADD_FINANCIAL_DATA: 'ADD_FINANCIAL_DATA',
  ADD_REAL_DATA: 'ADD_REAL_DATA',
  ADD_REAL_RAITING_VALUATION: 'ADD_REAL_RAITING_VALUATION',
  ADD_FINANCIAL_RAITING_VALUATION: 'ADD_FINANCIAL_RAITING_VALUATION',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',

  SET_TOASTR: 'SET_TOASTR',
}
export default storeConstants
